### ISSUE TITLE
Start Debug -> 504 Gateway Time-Out

### ISSUE THREAD

**Issue by 0x3e4** [gt732/FortiGPT#9]
Hey!  
First of all hats off for developing this tool! I was quite excited about it and just wanted to test it on my FW but every time when i try to "Start Debug" for "System > High CPU" it throws a "504 Gateway Time-Out" error.. any idea what it could be?

Textarea output is this:
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.23.4</center>
</body>
</html>
```

When i look into the FW logs then i can see that a few commands are successfully performed:  
- diagnose sys session full-stat
- diagnose sys top 5 20 3
- get system performance status
- get system console

On my admin account it even throws following:
`/bin/sh: 1: Syntax error: "(" unexpected`

Fortigate 200E (HA cluster) running 7.2.4

**Comment by gt732** [comment]
@0x3e4 hey! thanks for checking it out, I found the issue. Looks like the nginx reverse proxy is timing out since the backend script can take a bit of time to complete. I added the following command to the routes proxy_read_timeout 300s;. I also updated the docker images. Can you delete the images locally and redownload the new ones ? Let me know if it works out! 

```
location /express {
        rewrite /express/(.*) /$1 break;
        proxy_pass http://express;
        proxy_read_timeout 300s; <--
    }
```

**Comment by 0x3e4** [comment]
..and it worked! 💯
